### ISSUE TITLE
need help about game version

### ISSUE THREAD

**Issue by 8MiYile** [itsmeow/curseforge-upload#21]
https://www.curseforge.com/minecraft/mc-mods/customskinloader/files/4480815
This is a mod made by my friend that supports multiple versions, how do I fill in so many supported versions in the game_versions option?

**Comment by itsmeow** [comment]
Separate them with commas

**Comment by 8MiYile** [comment]
Can you help me with an example, for example, my mod supports Minecraft 1.18.* 1.19.* How would this be written?

**Comment by itsmeow** [comment]
You'd have to put all of them separately, there is no wildcards.

**Comment by 8MiYile** [comment]
I know there are no wildcards, so let me make it simpler
  1.18 , 1.18.1 , 1.19 , 1.19.1 , 1.19,2 , 1.19.3
So how do you write this?

**Comment by itsmeow** [comment]
You just write it like that without the spaces

`1.18,1.18.1,1.19.1` etc. no specific order is required or anything

**Comment by 8MiYile** [comment]
fabric or forge?

**Comment by itsmeow** [comment]
You can just write ,Fabric,Forge

As long as the number matches the text on the website

**Comment by 8MiYile** [comment]
oh okay

**Comment by 8MiYile** [comment]
If I want to upload both forge and fabric mod files, should I make both steps directly or?
example
CustomSkinLoader_ForgeActive.jar
CustomSkinLoader_Fabric.jar

**Comment by itsmeow** [comment]
You should add another workflow step

**Comment by 8MiYile** [comment]
```yaml
      -
        name: Publish Fabric to CurseForge 
        if: false
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/${{ steps.findjar.outputs.name_fabric_jar }}"
          game_endpoint: "minecraft"
          game_versions: "$(grep "minecraft_full_versions=" Fabric/build.properties | grep -v "#" | sed "s/$1=//g"),Fabric"
          project_id: "0"
          token: ${{ secrets.CURSEFORGE_API_KEY }}
      -
        name: Publish Forge Active to CurseForge 
        if: false
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/${{ steps.findjar.outputs.name_forge_active_jar }}"
          game_endpoint: "minecraft"
          game_versions: "$(grep "minecraft_full_versions=" Forge/Active/build.properties | grep -v "#" | sed "s/$1=//g"),Forge"
          project_id: "0"
          token: ${{ secrets.CURSEFORGE_API_KEY }}
```
Can it be changed to
```yaml
      -
        name: Publish to CurseForge 
        if: false
        uses: itsmeow/curseforge-upload@v3
        with:
          -
            file_path: "build/libs/${{ steps.findjar.outputs.name_fabric_jar }}"
            game_endpoint: "minecraft"
            game_versions: "$(grep "minecraft_full_versions=" Fabric/build.properties | grep -v "#" | sed "s/$1=//g"),Fabric"
            project_id: "0"
            token: ${{ secrets.CURSEFORGE_API_KEY }}
         -
            file_path: "build/libs/${{ steps.findjar.outputs.name_forge_active_jar }}"
            game_endpoint: "minecraft"
            game_versions: "$(grep "minecraft_full_versions=" Forge/Active/build.properties | grep -v "#" | sed "s/$1=//g"),Forge"
            project_id: "0"
            token: ${{ secrets.CURSEFORGE_API_KEY }}  
```
