### ISSUE TITLE
Get output fileID of CurseForge to append to URL

### ISSUE THREAD

**Issue by Macleykun** [itsmeow/curseforge-upload#6]
When a file/mod is uploaded to CF, it'll be displayed under the following URL:
https://www.curseforge.com/minecraft/mc-mods/notfmcplease/files/3531003

That last part: 3531003 is something i would want to append to a message i post on discord like:

messagefordiscord: Hey you can download the file at: https://www.curseforge.com/minecraft/mc-mods/notfmcplease/files/${{ thatfile_id }}

I'm pretty sure you've already included this at: https://github.com/itsmeow/curseforge-upload/blob/master/action.yml#L38
But i'm not sure what the name of that variable is :P

**Comment by itsmeow** [comment]
The name is `id`! so `steps.upload.outputs.id`, in the workflow you have to set the id of the step to `upload` to access it with that notation

**Comment by itsmeow** [comment]
```yaml
jobs:
  example:
    steps:
    - uses: actions/checkout@v1
    - name: Upload
      id: upload
      uses: itsmeow/curseforge-upload@master
      with:
        # ...
    - name: Discord
      content: https://curseforge.com/.../${{steps.upload.outputs.id}}
```
